### ISSUE TITLE
An error occurred while running the program

### ISSUE THREAD

**Issue by nalanyu2000** [choltz95/MTGP-NN#2]
Dear author,
When I run the code, an error occurred as following. I run the code in several versions of pytorch and gpytorch to rule out possible system problems. However, same error occured
Traceback (most recent call last):                                                                                
  File "/root/data/MTGP-NN-master/experiment.py", line 358, in <module>
    method.exp()
  File "/root/data/MTGP-NN-master/experiment.py", line 343, in exp
    self.loss_iterations, self.model = self.train(self.dataset.groups['train'], self.dataset.groups['test'])
  File "/root/data/MTGP-NN-master/experiment.py", line 164, in train
    loss = model.estimator.update(input_data_, labels_)
  File "/root/data/MTGP-NN-master/models.py", line 58, in update
    gp_output = self.interpolation_model(x_eval, task_idx)
  File "/root/anaconda3/lib/python3.7/site-packages/gpytorch/models/exact_gp.py", line 280, in __call__
    train_output = super().__call__(*train_inputs, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/gpytorch/module.py", line 28, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/data/MTGP-NN-master/models.py", line 176, in forward
    covar=covar_x.mul(covar_i)
  File "/root/anaconda3/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 1162, in mul
    return self._mul_matrix(lazify(other))
  File "/root/anaconda3/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 506, in _mul_matrix
    return NonLazyTensor(self.evaluate() * other.evaluate())
  File "/root/anaconda3/lib/python3.7/site-packages/gpytorch/utils/memoize.py", line 59, in g
    return _add_to_cache(self, cache_name, method(self, *args, **kwargs), *args, kwargs_pkl=kwargs_pkl)
  File "/root/anaconda3/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 906, in evaluate
    res = self.matmul(eye)
  File "/root/anaconda3/lib/python3.7/site-packages/gpytorch/lazy/interpolated_lazy_tensor.py", line 402, in matmul
    right_interp_res = left_t_interp(self.right_interp_indices, self.right_interp_values, tensor, base_size)
  File "/root/anaconda3/lib/python3.7/site-packages/gpytorch/utils/interpolation.py", line 230, in left_t_interp
    summing_matrix = cls(summing_matrix_indices, summing_matrix_values, size)
RuntimeError: found negative index -1 for dim 1

**Comment by choltz95** [comment]
Hi, sorry for the mess! I haven't touched this in a long time. It looks like the issue occurred around [L168](https://github.com/choltz95/MTGP-NN/blob/master/models.py#L168) in models.py

Could you verify the input to the update step in [L164](https://github.com/choltz95/MTGP-NN/blob/master/experiment.py#L164) in experiment.py & that parameters & shape are correct when instantiating the multi-task covariance matrices? As well as x_eval, task_idx when you call the interpolation model [L56](https://github.com/choltz95/MTGP-NN/blob/master/models.py#L56)?

**Comment by FirstDiscoverer** [comment]
I have same error.  and I also run the code in several versions of pytorch and gpytorch to rule out possible system problems.
I use the following version:
```
tqdm
pandas
# Python 3.7
gpytorch==0.3.5
torch==1.2

matplotlib
fire
```

**experiment.py** - [L164](https://github.com/choltz95/MTGP-NN/blob/master/experiment.py#L164) ：
input_data_： List[List[Tensor(56,), Tensor(56,), Tensor(56,)], List[Tensor(63,), Tensor(63,), Tensor(63,)],  List[Tensor(70,), Tensor(70,), Tensor(70,)], ...]
labels: List[Tensor(1,8), Tensor(1,9), Tensor(1,10), ...]

**models.py** - [L56](https://github.com/choltz95/MTGP-NN/blob/master/models.py#L56)：
x_eval：Tensor(8)
task_idx：Tensor(8)

**models.py** - [L168](https://github.com/choltz95/MTGP-NN/blob/master/models.py#L168)
covar_x: (56, 56)
covar_i: (56, 56)

When running `covar = covar_x.mul(covar_i)`, an error occurs `RuntimeError: found negative index -1 for dim 1`

by the way, I use the following code in Class Dataset to limit the amount of data for debugging

```
    @classmethod
    def load(cls, filepath):
        print(f"\nloading data file, path={filepath}")
        filepath = Path(filepath)
        with filepath.open('rb') as f:
            _data = pickle.load(f)
            data = cls.limit_data(_data)
            return data

    @staticmethod
    def limit_data(data):
        max_data = 500
        if max_data:
            print(f"limit data, max_data={max_data}")
            for split_key, values in data.groups.items():
                for k, v in values.items():
                    data.groups[split_key][k] = v[:max_data]
        return data
```
